# Generated by Django 5.1.4 on 2025-01-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('length_of_service', models.CharField(choices=[('<1', 'Less than 1 year'), ('1-3', '1–3 years'), ('3-5', '3–5 years'), ('>5', 'More than 5 years')], max_length=50)),
                ('work_environment', models.CharField(max_length=50)),
                ('work_life_balance', models.CharField(max_length=50)),
                ('resources', models.CharField(max_length=50)),
                ('professional_growth', models.CharField(max_length=50)),
                ('recognition', models.CharField(max_length=50)),
                ('leadership_communication', models.CharField(max_length=50)),
                ('teamwork', models.CharField(max_length=50)),
                ('diversity_inclusion', models.CharField(max_length=50)),
                ('conflict_resolution', models.CharField(max_length=50)),
                ('positives', models.TextField(blank=True, null=True)),
                ('improvements', models.TextField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
